### PR TITLE
Add background image

### PR DESCRIPTION
**Pull request by VegaFromLyra**
image

image
### Changes include:
- Adding a stock background image
- Cleaning up the constraints usage
### ToDo
- [x] There's an access violation the first time a user logs in so needs to fix that up

### CODE REVIEW

**Comment by VegaFromLyra** [comment]
@akshay23 Review time!

**Comment by akshay23** [comment]
:+1:

**Comment by akshay23** [comment]
Can turn down the opacity of the background image by maybe 20 to 20% ? 
You can do this by setting the images alpha value. Look for the line of code in MainViewController.cs that sets the album artwork's alpha. (imgArtwork.alpha)

**Comment by VegaFromLyra** [comment]
Done!

**Pull request merged**
